version: '3.9'

services:
  user-interface:
    build:
      context: ./user-interface
      dockerfile: Dockerfile.prod
    environment:
      - PORT=80
    image: "aasm/li-user-interface:${VERSION}"
    networks:
      - proxy-net
    volumes:
      - user-interface-data:/app/node_modules

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile.prod
    image: "aasm/li-proxy:${VERSION}"
    ports:
      - "80:80"
      - "8008:7687"
    networks:
      - proxy-net
      - external-li-sre-net

networks:
  proxy-net:
  external-li-sre-net:
    external: true
    name: li-sre

volumes:
  user-interface-data:
