version: '3.9'

services:
  user-interface:
    build:
      context: ./user-interface
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001
    image: 127.0.0.1:5000/li-user-interface
    networks:
      - li-net
      - external-li-sre-net
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./user-interface/src:/app/src

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    image: 127.0.0.1:5000/li-proxy
    ports:
      - "3002:80"
    networks:
      - li-net
      - external-li-sre-net

networks:
  li-net:
  external-li-sre-net:
    external: true
    name: li-sre
