version: '3.9'

services:
  user-interface:
    build:
      context: ./user-interface
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
    image: madpeh/li-user-interface
    networks:
      - proxy-net
    volumes:
      - /app/node_modules
      - ./user-interface/src:/app/src

  proxy:
    build: ./proxy
    image: madpeh/li-proxy
    ports:
      - "80:80"
      - "8008:7687"
    networks:
      - proxy-net
      - external-li-sre-net

networks:
  proxy-net:
  external-li-sre-net:
    external: true
    name: li-sre
