FROM node:16.3.0-alpine3.13 as build-env
WORKDIR /app
COPY . .
RUN npm ci && npm run build

FROM node:16.3.0-alpine3.13
WORKDIR /app
COPY --from=build-env /app/build /app/build
RUN npm install -g serve@13.0.2
CMD [ "sh", "-c", "serve build --single --listen ${PORT}" ]
