FROM node:16.19.0-alpine3.17 as build-env
WORKDIR /app
COPY package* .
RUN npm ci
COPY . .
RUN npm run build

FROM node:16.19.0-alpine3.17
WORKDIR /app
COPY --from=build-env /app/build /app/build
RUN npm install -g serve@14.1.2
CMD [ "sh", "-c", "serve build --single --listen ${PORT}" ]
