FROM node:16.13-alpine
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
ENV PORT=3001
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --silent
RUN yarn add react-scripts@4.0.3 --silent
COPY . ./
RUN yarn build
CMD ["yarn", "start"]