export const pingpong = [
  'MESSAGE ping_pong,Inform',
  'PRM data,float',
  'EMESSAGE',
  '',
  'AGENT PingPonger',
  'PRM popularity,float,dist,normal,5,1',
  'BEHAV hello, setup',
  'ACTION hello,send_msg, ping_pong, Inform',
  'SET     SEND.data,popularity',
  'SEND    connections',
  'EACTION',
  'EBEHAV',
  'BEHAV pong,msg_rcv,ping_pong,Inform',
  'ACTION update_self,modify_self',
  'ADD     popularity,RCV.data',
  'EACTION',
  'ACTION pong,send_msg, ping_pong, Inform',
  'SET     SEND.data,popularity',
  'SEND    RCV.sender',
  'EACTION',
  'EBEHAV',
  'EAGENT',
  '',
  'GRAPH statistical',
  'SIZE 100',
  'DEFG PingPonger, 100%, 10',
  'EGRAPH',
  ''
]

export const benchmark = [
  'MESSAGE facebook_post, query',
  'PRM photos, float',
  'EMESSAGE',
  '',
  'AGENT average_user',
  'PRM friends, list, conn',
  'PRM saved_posts, list, msg',
  '',
  'BEHAV facebook_activity, cyclic, 30',
  'ACTION post_photos, send_msg, facebook_post, query',
  'DECL num_photos, 0',
  'RAND num_photos, int, normal, 21, 37',
  'SET send.photos, num_photos',
  'SEND connections',
  'EACTION',
  'EBEHAV',
  '',
  'BEHAV read_posts, msg_rcv, facebook_post, query',
  'ACTION add_friends, modify_self',
  'ADDE friends, rcv.sender',
  'EACTION',
  'ACTION save_posts, modify_self',
  'ADDE saved_posts, rcv',
  'EACTION',
  'EBEHAV',
  'EAGENT',
  '',
  'GRAPH statistical',
  'SIZE 3000',
  'DEFG average_user, 100%, dist_normal, 0, 15',
  'EGRAPH',
  ''
]
